### ISSUE TITLE
Command output empty on example dataset

### ISSUE THREAD

**Issue by rmadnantariq** [MattiaPandolfoVR/MetaPhage#43]
Hi,
I have been trying to work with the example dataset and I got this error is there something I'm doing wrong?

Thanks

Error executing process > 'vibrant (megahit-SRR8652861)'

Caused by:
  Process `vibrant (megahit-SRR8652861)` terminated with an error exit status (1)

Command executed:

  VIBRANT_run.py         -t 16         -i SRR8652861_megahit_contigs.fasta         -d /home/crk_tgms5/MetaPhage/db/vibrant/legacy/         -m /home/crk_tgms5/MetaPhage/db/vibrant/legacy/         -virome
  mv VIBRANT_*/ SRR8652861_vibrant/
  sed 's/^>/>vibrant_/' SRR8652861_vibrant/VIBRANT_phages_SRR8652861_megahit_contigs/SRR8652861_megahit_contigs.phages_combined.fna >         SRR8652861_vibrant/VIBRANT_phages_SRR8652861_megahit_contigs/SRR8652861_correct_vibrant.fna
  rm -f temp*

Command exit status:
  1

Command output:
  (empty)

Command error:
  /cm/local/apps/environment-modules/4.0.0//init/bash: line 15: MODULES_USE_COMPAT_VERSION: unbound variable
  Traceback (most recent call last):
    File "/home/crk_tgms5/miniconda/envs/MetaPhage/bin/VIBRANT_annotation.py", line 1708, in <module>
      AMG_dict.update({str(annotations[n]):str(annotations[n+1]).replace("$~&", " ").replace('^@%','"') + '\t' + str(annotations[n+2]) + '\t' + str(ko_name) + '\t' + str(annotations[n+6]) + '\t' + str(pfam_name)})
  NameError: name 'pfam_name' is not defined
  Traceback (most recent call last):
    File "/home/crk_tgms5/miniconda/envs/MetaPhage/bin/VIBRANT_run.py", line 633, in <module>
      with open(str(out_folder)+'VIBRANT_AMG_individuals_' + str(base) + '.tsv', 'r') as annotations:
  FileNotFoundError: [Errno 2] No such file or directory: 'VIBRANT_AMG_individuals_SRR8652861_megahit_contigs.tsv'

Work dir:
  /home/crk_tgms5/MetaPhage/work/0d/98d8f82c8bfa2d1a2073b0c0f57814

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by telatin** [comment]
Can you please provide your configuration file? Did you use Singularity or created a Conda environment?

**Comment by rmadnantariq** [comment]
[demo.txt](https://github.com/MattiaPandolfoVR/MetaPhage/files/8590104/demo.txt)
Hi I used Conda environment and cloned the repository.
