### ISSUE TITLE
Error on the downloading the databases

### ISSUE THREAD

**Issue by matveykolesnik** [MattiaPandolfoVR/MetaPhage#47]
Greetings,

I am trying to reproduce the tutorial (https://mattiapandolfovr.github.io/MetaPhage/tutorial), and I got the following errors at the stage of downloading the databases:

`./bin/python/db_manager.py -o ./db/ -m 6
db_manager.py requires wget to be installed
 📦  Preparing to download PhiX reference
 📦  Preparing to download MiniKraken
 📦  Preparing to download Vibrant
 📦  Preparing to download Virsorter
 📦  Preparing to download Phigaro
 📦  Preparing to download vConTACT2
 ✅  PhiX reference downloaded
 ✅  vConTACT2 downloaded

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

As far as I can see, all databases except vConTACT2 could be downloaded (I see the corresponding catalogs in ${METAPHAGE_DIR}/db). Unfortunately, I cannot realize what is going wrong, thus I cannot fix this error.

Perhaps you could help me with it?

Sincerely,
Matvey

**Comment by telatin** [comment]
there are maintenance works in the hosting; they should terminate in a few days, meanwhile, I will check for alternatives. Thanks for sharing

**Comment by matveykolesnik** [comment]
Thank you for your response!
