### ISSUE TITLE
Any chance the CPU requirement could be lowered?

### ISSUE THREAD

**Issue by janzheng** [MattiaPandolfoVR/MetaPhage#48]
e.g. lower the requirement `fastp -w 16` — are there other steps that require 16 cores?

Lowering the requirement will make it easier to run on slower machines (though of course it'll way longer but I'm ok with that). Or are there software limitations that require 16 cores?

Just adding that this param configuration doesn't seem to lower it:
```
// Define the maximum resources
params {
  max_cpus = 8
  max_memory = 60.GB
  max_time = 72.h
}
```

Edit #2: changing the values in `nextflow.config` `process { withLabel: { ... } }` and `params { max_cpus = # }` fixed it for me! Ok to close.

Please update docs to make it apparently that's where you should edit (I was editing the demo.conf file), for those new to Nextflow

**Comment by telatin** [comment]
Yes, nextflow configuration is a great way to tune the pipeline, and we hope to make it more flexible in the future.

**Comment by janzheng** [comment]
In a similar vein, if we run into a config issue during a long run, does Metaphage "pick up from where you left off" or does it re-run all processes?

**Comment by telatin** [comment]
Good question. You can add -resume but if there are changes that could theoretically affect the beginning resume might not work as expected. With other pipelines I had to extend the timeout and I’m unsure how it went. Out of curiosity what config is needed to change?

**Comment by janzheng** [comment]
I set the metadata config wrong for the last visualization step (I had a typo in the column name of the CSV) which stopped the entire thing out.

Definitely agreed that 99% of the cases you should re-run though!
