### ISSUE TITLE
Adding Phamb viral contigs to MetaPhage

### ISSUE THREAD

**Issue by bhimbbiswa** [MattiaPandolfoVR/MetaPhage#49]
Hi,

Thank you very much for making this great pipeline.

I will start using this pipeline from today with my shotgun metagenome samples.

But I also viral contigs generated using Phamb (https://github.com/RasmussenLab/phamb) from the same samples.

Is there any way I can add these contigs in the dereplication stage of MetaPhage?

Regards,

Bhim

**Comment by MattiaPandolfoVR** [comment]
Hi @bhimbbiswa, thank for using MetaPhage!
Regarding contigs as input, unfortunately at the moment it is not supported, but i am working on it and it will definitely be a feature in a next release!
Please feel free to share any other feedback or suggestion!
Kind reagards,
Mattia

**Comment by bhimbbiswa** [comment]
Dear @MattiaPandolfoVR .

Thank you very much for your kind reply.

If I am stuck or have any doubt I will surely raise it here.

Regards,

Bhim
