### ISSUE TITLE
Discarding human reads

### ISSUE THREAD

**Issue by mhmism** [MattiaPandolfoVR/MetaPhage#53]
Hello, 

Thanks again for this amazing work. I wonder whether host (human) reads are removed at the preprocessing step. I only see the removal of the PhiX 174 genome, so not so sure whether there is another step that removes the host genome (I think this step is pretty standard in other metagenomics preprocessing pipelines). 
If the host reads are not removed, do you think this will affect the latter steps of bacterial taxonomy and bacteriophage identification?

**Comment by telatin** [comment]
You can preprocess the reads using https://github.com/telatin/cleanup to remove the human host, as this is a project specific step while PhiX can be found virtually in any Illumina dataset.
Cheers

**Comment by mhmism** [comment]
Thanks for sharing the cleanup tool. I think it would be nice to add a note to the reader highlighting that host reads still need to be removed (or add this step in next version updates).
