### ISSUE TITLE
Link for downloading databases are down

### ISSUE THREAD

**Issue by JulianGarneau** [MattiaPandolfoVR/MetaPhage#58]
Hello, and thank you for developing MetaPhage,

Just wanted to point out that all the links to download the databases hosted on the s3.climb.ac.uk are not working and makes it impossible to install the MetaPhage2 version.

For MetaPhage1, we can still use the zenodo link you provided for Inphared, but all the links are not present on zenedo for the new version of metaphage.

Looking forward to install and test MetaPhage2!

Warm regards, Julian

**Comment by telatin** [comment]
Hello and thanks for reporting, 
MetaPhage1 link has been fixed in 0.3.3 (https://mattiapandolfovr.github.io/MetaPhage/tutorial), let us know if now it works for you
