### ISSUE TITLE
An error with heatmap(megahit) of MetaPhage v2 beta

### ISSUE THREAD

**Issue by ilnamkang** [MattiaPandolfoVR/MetaPhage#59]
Hi,

I encountered an error with heatmap(megahit) step of MetaPhage v2 beta.

Below is the error message.

\-----
Error executing process > 'heatmap (megahit)'

Caused by:
  Process `heatmap (megahit)` terminated with an error exit status (1)

Command executed:

  Rscript /home/kangin/Programs/MetaPhage.V2/bin/Rscript/heatmap.R count_table.csv taxonomy_table.csv metadata.csv Sample

Command exit status:
  1

Command output:
   [1] "Closer"         "Accession"      "Status"         "VC"            
   [5] "Level"          "Weight"         "Host"           "BaltimoreGroup"
   [9] "Realm"          "Kingdom"        "Phylum"         "Class"         
  [13] "Order"          "Family"         "Subfamily"      "Genus"         

Command error:
  Error in h(simpleError(msg, call)) : 
    error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': incorrect number of dimensions
  Calls: as.data.frame -> .handleSimpleError -> h
  Execution halted

Work dir:
  /home/kangin/Programs/MetaPhage.V2/work/43/e676af10556ccd47e3f57f0541b464

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
\-----

I analyzed only two samples (viromes), and the metadata file contained only one column named "Sample".

Is this error due to too small number of samples or metadata fields, or due to a bug?

Thank you.

**Comment by MattiaPandolfoVR** [comment]
Hi there,
your error is related to the metadata having only the "Sample" column. MetaPhage needs the metadata file to have at least one column filled with your variables of interest, to use it in the various plots (heatmap, alpha diversities, violin plots etc.). If you are interested in the plots, you have to specify the column of interest in your config file for each plot, (e.g.  heatmap_var = "Treatment", alpha_var1, alpha_var2 etc.).

**Comment by ilnamkang** [comment]
Thank you for explanation.
