### ISSUE TITLE
Link for developmental version MetaPhage2 not accessible

### ISSUE THREAD

**Issue by JulianGarneau** [MattiaPandolfoVR/MetaPhage#60]
As mentionned in a previous issue, some of the download links for developmental version of MetaPhage2are still not accessible:

I think you mentionned that the link for Metaphage1 has been solved, but I encounter the same problem for the Metaphage2 links... All those related to the uk server apparently:

https://s3.climb.ac.uk/ifrqmra-metaphage/v2.0/virsorter2.tar.gz

https://s3.climb.ac.uk/ifrqmra-metaphage/v2.0/checkv.tar.gz

https://s3.climb.ac.uk/ifrqmra-metaphage/v2.0/inphared.tar.gz

Thank you very much

**Comment by telatin** [comment]
They should be patched in [dev](https://github.com/MattiaPandolfoVR/MetaPhage/blob/dev/bin/python/db_manager.py) now as well, in case just replace `s3.climb` with `warwick.s3.climb` in your local copy :)
