### ISSUE TITLE
Link for metaphage (v1.0) singularity image down

### ISSUE THREAD

**Issue by Drjameswynne** [MattiaPandolfoVR/MetaPhage#61]
It appears the link to singularity image is down.  Running:

wget -O $METAPHAGE_DIR/containers/metaphage.simg "https://s3.climb.ac.uk/ifrqmra-metaphage/v1.0/metaphage.simg"

generates the following error:

--2023-03-24 15:41:12--  https://s3.climb.ac.uk/ifrqmra-metaphage/v1.0/metaphage.simg
Resolving s3.climb.ac.uk (s3.climb.ac.uk)... 147.188.173.14
Connecting to s3.climb.ac.uk (s3.climb.ac.uk)|147.188.173.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-24 15:41:13 ERROR 404: Not Found.

Is there a newer link I can access?

**Comment by telatin** [comment]
Sorry, it was migrated to 
[https://warwick.s3.climb.ac.uk/ifrqmra-metaphage/v1.0/metaphage.simg](https://warwick.s3.climb.ac.uk/ifrqmra-metaphage/v1.0/metaphage.simg)
