### ISSUE TITLE
Out of memory error at the Qualimap bamqc step

### ISSUE THREAD

**Issue by ilnamkang** [MattiaPandolfoVR/MetaPhage#71]
Hi,

I'm experiencing an out of memory error at the Qualimap bamqc step.

Below is the error message.
\======
Command error:
  Building a SMALL index
  59516449 reads; of these:
    59516449 (100.00%) were paired; of these:
      9508796 (15.98%) aligned concordantly 0 times
      11383356 (19.13%) aligned concordantly exactly 1 time
      38624297 (64.90%) aligned concordantly >1 times
      ----
      9508796 pairs aligned concordantly 0 times; of these:
        500477 (5.26%) aligned discordantly 1 time
      ----
      9008319 pairs aligned 0 times concordantly or discordantly; of these:
        18016638 mates make up the pairs; of these:
          11278938 (62.60%) aligned 0 times
          528133 (2.93%) aligned exactly 1 time
          6209567 (34.47%) aligned >1 times
  90.52% overall alignment rate
  [bam_sort_core] merging from 48 files and 16 in-memory blocks...
  
  WARNING: out of memory!
  Qualimap allows to set RAM size using special argument: --java-mem-size
  Check more details using --help command or read the manual.
\======

---
Hinted at the error message, I edited Qualimap part of "main.nf" file as follows. I added "--java-mem-size=24G" to the file.
\======
    qualimap bamqc \
    -nt ${task.cpus} \
    -outdir qualimap_bamqc_${seqID}_${consensus}.folder \
    -bam ${seqID}_${consensus}.sorted.bam
    --java-mem-size=24G
    """
\======

But, when I resumed the run with the edited main.nf file, I encountered another error. The error message is as below.
\======
Command error:
  Building a SMALL index
  12889292 reads; of these:
    12889292 (100.00%) were paired; of these:
      7319646 (56.79%) aligned concordantly 0 times
      1388181 (10.77%) aligned concordantly exactly 1 time
      4181465 (32.44%) aligned concordantly >1 times
      ----
      7319646 pairs aligned concordantly 0 times; of these:
        29667 (0.41%) aligned discordantly 1 time
      ----
      7289979 pairs aligned 0 times concordantly or discordantly; of these:
        14579958 mates make up the pairs; of these:
          13283039 (91.10%) aligned 0 times
          179847 (1.23%) aligned exactly 1 time
          1117072 (7.66%) aligned >1 times
  48.47% overall alignment rate
  [bam_sort_core] merging from 0 files and 16 in-memory blocks...
  .command.sh: line 9: --java-mem-size=24G: command not found
\======

It seems that the addition of "--java-mem-size=24G" has caused this error.

How can I solve this problem?

Thanks.

**Comment by MattiaPandolfoVR** [comment]
Hi there,
looking at the code you posted above, it might be a little mistake. Did you use the \ between the lines? e.g.
`qualimap bamqc \
-nt ${task.cpus} \
-outdir qualimap_bamqc_${seqID}${consensus}.folder \
-bam ${seqID}${consensus}.sorted.bam \
--java-mem-size=24G`

Maybe you missed the one after `-bam ${seqID}${consensus}.sorted.bam` line(?)
If it's not that, let me know and i'll try to replicate this issue ;)

**Comment by ilnamkang** [comment]
Thank you for pointing out my mistake correctly. I forgot to add \ after the line that you indicated.

After correcting the mistake, Qualimap is running without any errors.
